name: Workflow-onedrive-automatization

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' 

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    env:
       ARTIFACT_FOLDER: 'artifacts'
       
    steps:
      - name: Checkout (este repo)
        uses: actions/checkout@v4
      
      - name: Download artifacts from supermercados-code
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: solutionsmateus/workflow-github-action
          workflow: vm-solutions-mateus.yml
          branch: main
          name: "*"                      
          path: ${{ env.ARTIFACT_FOLDER }} 
          if_no_artifact_found: warn
          token: ${{ secrets.MEUPAT }} 

      - name: Setup Python v.3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency: requirements.txt 

      - name: Instalar requirements.txt
        shell: pwsh
        run: |
          # Comando corrigido para instalar dependências
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lista todos os artifacts baixados
        shell: pwsh
        run: |
          echo "Conteúdo de artifacts:"
          # Usa a variável de ambiente
          Get-ChildItem -Recurse ${{ env.ARTIFACT_FOLDER }} | Select-Object FullName, Length

      - name: Configurar RClone (Secrets)
        uses: AnimMouse/setup-rclone@v1
        with: 
           rcloneconfigbase: ${{ secrets.RCLONE_CONFIG_BASE64 }} 

      - name: Executar o Script (App.py) e Sincronizar
        shell: pwsh
        run: |
           echo "Iniciando a organização e sincronização dos arquivos."
           # Execução direta do script Python
           python app.py